### ISSUE TITLE
Swift 3 and iOS 10 Support

### ISSUE THREAD

**Issue by Sun3** [iwasrobbed/RPCircularProgress#10]
Will there be a Swift 3 and iOS 10 Support. Currently there are lot's of compile errors.

Thank you.

**Comment by iwasrobbed** [comment]
I'll be having a look at this over the weekend. Pull requests always welcome as well

**Comment by iwasrobbed** [comment]
- Swift 3.0 branch: [`swift/3.0`](https://github.com/iwasrobbed/RPCircularProgress/tree/swift/3.0) and Cocoapods version of the pod is 0.3.0
- Swift 2.3 branch: [`swift/2.3`](https://github.com/iwasrobbed/RPCircularProgress/tree/swift/2.3) and Cocoapods version of the pod is 0.2.3
