### ISSUE TITLE
Swift 3 to Objc Generated interface 

### ISSUE THREAD

**Issue by david2Coders** [iwasrobbed/RPCircularProgress#18]
Im trying to use in an old project (Objc one) the library, but i notice that the generated interface didn't show all the methods ( the ones at the extensions). 

Basically I invoke the method updateProgress

**Comment by iwasrobbed** [comment]
@david2Coders By default, specialized Swift features like default parameters won't be bridged into ObjC and I don't plan to support that or ObjC. You are free to fork the repo if you need that (an old branch < Swift 3 already existed for that purpose but has not been updated: https://github.com/iwasrobbed/RPCircularProgress/tree/objc)
