### ISSUE TITLE
just a noob question

### ISSUE THREAD

**Issue by spurdow** [iwasrobbed/RPCircularProgress#19]
how do i add this on alert view?

**Comment by iwasrobbed** [comment]
`UIAlertController` isn't really meant to have subviews added to it (and [Apple's docs](https://developer.apple.com/reference/uikit/uialertcontroller) discourage it).

>The view hierarchy for this class is private and must not be modified

There are [some who still do it](http://stackoverflow.com/a/40699719/308315) but I'd likely just create your own modal ([example here](https://gist.github.com/iwasrobbed/0f7d81c69ab3daaf2c1d5b54067e4ac4) or use something like [SVProgressHUD](https://github.com/SVProgressHUD/SVProgressHUD)
