### ISSUE TITLE
Dot Appears every time updateProgress is called.

### ISSUE THREAD

**Issue by mmasque** [iwasrobbed/RPCircularProgress#21]
I've added a `RPCircularProgress` to my view controller via storyboard, and in the view controller's class, I call `updateProgress`, a white dot appears on the screen. The dot actually moves with the bar as it fills up. 
I'm using the Swift 2.3 version with the AnimationDelegate commented out as CAAnimation isn't supported by Swift 2.1.

**Comment by iwasrobbed** [comment]
Hi @mmasque, you can checkout the original Swift 2 version with this commit `git checkout -b swift2 7bff739648a955300460b5d98981aafad9ef7e20` (but I don't use storyboards so I can't say if it ever worked with those or not).

Unfortunately I don't have the free time available to debug older versions. If you happen to see it in a newer version, feel free to open an issue w/ a sample project showing it.
