### ISSUE TITLE
UpdateProgress not available from Objective C

### ISSUE THREAD

**Issue by Denages** [iwasrobbed/RPCircularProgress#23]
There is no UpdateProgress: method in RPCircularProgress-Swift.h. Also the "progress" property is readonly. How can I set a progress value from within Objective C project?

**Comment by iwasrobbed** [comment]
This library wasn't created for Obj-C portability; it's easy enough to add by just forking this repo and making Obj-C equivalent methods that don't use certain Swift features (like default values in the method signature).

An old, outdated version of that is here if you need an example to go off of: https://github.com/iwasrobbed/RPCircularProgress/tree/objc
