### ISSUE TITLE
This can lead to engine corruption and weird crashes

### ISSUE THREAD

**Issue by ashish12s3** [iwasrobbed/RPCircularProgress#25]
This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

**Comment by iwasrobbed** [comment]
We don't use any background threads in the source code (nor do we use any autolayout), so I'm guessing this is coming from your app doing something and then updating the UI asynchronously? I'd check any network code you may have.

You may also want to look at https://stackoverflow.com/questions/32680303/ios9-this-application-is-modifying-the-autolayout-engine-from-a-background-thr?noredirect=1&lq=1
