### ISSUE TITLE
libswiftXCTest.dylib   Reason: image not found

### ISSUE THREAD

**Issue by samsidd** [iwasrobbed/RPCircularProgress#32]
I am getting this wierd crash right after installing this as a pod and running the application

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/colworx/Library/Developer/CoreSimulator/Devices/8F5D5AC5-3A58-4577-AAC1-BA1A170D728C/data/Containers/Bundle/Application/E1DE38E0-B483-4CD5-A6E8-2665EF17EEAB/squad.app/Frameworks/libswiftXCTest.dylib
  Reason: image not found

**Comment by iwasrobbed** [comment]
Seems like you're installing this to the wrong (testing) target and don't have the XCTest framework linked properly in your project.

If you look at the [podspec](https://github.com/iwasrobbed/RPCircularProgress/blob/master/RPCircularProgress.podspec), you'll see it just adds one file to the project, which doesn't import XCTest
