### ISSUE TITLE
s.swift_version = '4.2' missing from podspec

### ISSUE THREAD

**Issue by kamrankhan07** [iwasrobbed/RPCircularProgress#34]
Please add s.swift_version = '4.2' to podspec

**Comment by alex-taffe** [comment]
@kamrankhan07 I can try this weekend or just make a PR if you want

**Comment by kamrankhan07** [comment]
@alex-taffe I added directly on Github, didn't test but should be fine

**Comment by iwasrobbed** [comment]
Closed in #35 , thanks again 👍
