### ISSUE TITLE
Xcode 10.2 / Swift 5 support

### ISSUE THREAD

**Issue by robertveringa89** [iwasrobbed/RPCircularProgress#36]
Any chance you will create a new pod version for Xcode 10.2 / Swift 5 support?

**Comment by alex-taffe** [comment]
I can try to get this taken care of later today

**Comment by robertveringa89** [comment]
Thanks for the quick reply! Looking forward to it.

**Comment by iwasrobbed** [comment]
Closed in https://github.com/iwasrobbed/RPCircularProgress/pull/37 (thanks @alex-taffe)
