### ISSUE TITLE
Hello, Can with set progress label that show percentage?

### ISSUE THREAD

**Issue by Ashish2015** [iwasrobbed/RPCircularProgress#38]

**Comment by alex-taffe** [comment]
I’m not sure I understand, can you elaborate a bit more?

**Comment by iwasrobbed** [comment]
From the docs:

>var progress: CGFloat
>
>Getter for the current progress (not observed from any active animations)

You're also updating the progress yourself, so you should know this value in advance when you update the progress bar with the new progress value (and use it to update any labels)
